language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - npm install -g eslint-config-airbnb@14.1.0 eslint@3.19.0 eslint-plugin-jsx-a11y@4.0.0 eslint-plugin-import@2.2.0 eslint-plugin-react@6.10.3
env:
  global:
    - secure: >-
        HWwX1XiMfkZkC5XzAz6HkMJcFR+O1DZ+g9hnogZ0e3zdjqZ8VFkCsx0glJLA4TIPdWDfq93gRmeGtbepIx0x4BVOWX8rqoIjb9fbNJDU4ItZsbOvDLInFqKevdq+/klDavVfbR4hNeaHgDmcIEa/IolDU0qIrIdefBfZLOQ0ajM=
    - secure: >-
        hBkZz41jJfEP+Z8Uwcw3/EWDLLBzKT+WKY/XI7ubT/bxlXn95RJqY+j1pBX7+fHfLrUfjRmQHTsqkkST2JwRGAZoZpBX+lmUuNRyMoYsDKMl+CYinhSNTVVGSv7JPt5Ls5fktfzIt6Qd97vBy25hcCGKB6HBy+ppfP2DuII4uC8=
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - eslint .
  - xvfb-run polymer test --skip-plugin sauce --plugin local -l chrome;
dist: trusty